spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8:///

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    format-sql: false
